# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-20 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('f1', models.CharField(max_length=255)),
                ('f2', models.IntegerField()),
                ('f3', models.TextField()),
                ('f4', models.IntegerField()),
            ],
            options={
                'db_table': 'test_table',
            },
        ),
    ]
